import { CHARACTER_PORTRAITS, type CharacterDebrief, type OctopusDebrief } from './octopus';
import type { GhostStats } from './ghost-frame';
const URL='https://octopus-engine-app.benoitlubert.workers.dev/mission';
const fallback:CharacterDebrief[]=[
{name:'MARTY',role:'HYPOTHÈSE',text:"Quelque chose a peut-être clignoté. Pour une fois, attendons les chiffres avant d'accuser le Feuch."},
{name:'NIKOLAS',role:'CONTRÔLE',text:'Détections et faux positifs sont les données utiles. Une session isolée ne démontre rien.'},
{name:'LOLO',role:'RESSENTI',text:"Le plus étrange est parfois d'être certain d'avoir vu une forme qui n'était pas présentée."},
{name:'MAX',role:'COMMENTAIRE',text:'Le cerveau voit des trucs. Breaking news : il faisait déjà ça avant le laboratoire.'},
{name:'SLOBODANE',role:'THÉORIE',text:'Si un motif revient, sa répétition sera plus intéressante que son étrangeté.'},
{name:'NATASHA',role:'ANALYSE',text:'Session archivée. Je ne signalerai un motif que s’il réapparaît dans les données.'}];
function parse(raw:string):CharacterDebrief[]|null{try{const cleaned=raw.replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/i,'').trim();const p=JSON.parse(cleaned) as {characters?:unknown};if(!Array.isArray(p.characters))return null;const allowed=new Set(Object.keys(CHARACTER_PORTRAITS));const out=p.characters.flatMap(item=>{if(!item||typeof item!=='object')return[];const r=item as Record<string,unknown>;const name=typeof r.name==='string'?r.name.toUpperCase():'';const text=typeof r.text==='string'?r.text.trim():'';const role=typeof r.role==='string'?r.role:'DEBRIEF';return allowed.has(name)&&text?[{name:name as CharacterDebrief['name'],role,text}]:[]});return out.length===6?out:null}catch{return null}}
export async function requestGhostDebrief(stats:GhostStats):Promise<OctopusDebrief>{const id=`ghost_${Date.now()}`;const prompt=`Débrief Feuch Lab FLI-GHOST-02. Données réelles uniquement: ${JSON.stringify(stats)}. Personnages: ${Object.entries(CHARACTER_PORTRAITS).map(([n,p])=>`${n}: ${p}`).join('\n')}. Distingue mesure et hypothèse. Un faux positif signifie qu'une forme a été rapportée pendant un essai sans cible; ce n'est pas paranormal. Natasha ne doit inventer aucun motif ni prétendre à une répétition inter-session sans données. Retourne uniquement JSON {"characters":[{"name":"MARTY","role":"...","text":"..."}]} avec exactement MARTY,NIKOLAS,LOLO,MAX,SLOBODANE,NATASHA.`;try{const response=await fetch(URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({operationId:id,title:'Feuch Lab · Ghost Frame debrief',objective:'Interpret measured perception data without inventing anomalies.',requiredCapabilities:['content.generate'],authorizedResources:[],prompt,context:{id,label:'FLI-GHOST-02 debrief',objective:'Grounded perception debrief',metadata:{universe:'blacklace',experiment:'FLI-GHOST-02'}}})});if(!response.ok)throw new Error();const payload=await response.json() as {output?:Record<string,unknown>};const raw=typeof payload.output?.text==='string'?payload.output.text:'';const characters=parse(raw);if(!characters)throw new Error();return{characters,source:'octopus'}}catch{return{characters:fallback,source:'fallback'}}}
