import { useEffect, useMemo, useRef, useState } from 'react';
import { calculateWalkProtocol, type BodyParameters } from './domain/protocol';
import { analyzeMotion, type MotionSample } from './domain/analysis';
import { requestBlacklaceDebrief, type CharacterDebrief } from './domain/octopus';

type Screen = 'intro' | 'setup' | 'protocol' | 'walk' | 'results';
type VortexZone = { id: 'A'|'B'|'C'|'D'|'E'|'F'|'G'|'H'; name: string; y: number; side: 'center'|'left'|'right' };
const initialBody: BodyParameters = { weightKg: 75, heightCm: 175, shoeSizeEU: 42, availableDistanceM: 6 };
const phases: { id: Screen; n: number; label: string }[] = [
  { id:'setup', n:1, label:'Préparer' }, { id:'protocol', n:2, label:'Apprendre' },
  { id:'walk', n:3, label:'Expérimenter' }, { id:'results', n:4, label:'Débrief' },
];
const vortexZones: VortexZone[] = [
  {id:'A',name:'Couronne',y:8,side:'center'},{id:'B',name:'Œil spirituel',y:19,side:'right'},
  {id:'C',name:'Voix',y:30,side:'right'},{id:'D',name:'Cœur',y:43,side:'right'},
  {id:'E',name:'Organes inférieurs',y:57,side:'right'},{id:'F',name:'Batterie',y:69,side:'right'},
  {id:'G',name:'Sol',y:92,side:'center'},{id:'H',name:'Mains',y:48,side:'left'},
];

export default function App(){
  const [screen,setScreen]=useState<Screen>('intro');
  const [body,setBody]=useState<BodyParameters>(initialBody);
  const protocol=useMemo(()=>calculateWalkProtocol(body),[body]);
  const [step,setStep]=useState(0); const [running,setRunning]=useState(false); const [samples,setSamples]=useState<MotionSample[]>([]);
  const startedAt=useRef<number|null>(null);
  useEffect(()=>{ if(!running)return; const onMotion=(event:DeviceMotionEvent)=>{ const a=event.accelerationIncludingGravity; setSamples(current=>[...current.slice(-299),{t:performance.now(),ax:a?.x??null,ay:a?.y??null,az:a?.z??null}]);}; window.addEventListener('devicemotion',onMotion); return()=>window.removeEventListener('devicemotion',onMotion);},[running]);
  useEffect(()=>{ if(!running)return; const timer=window.setInterval(()=>setStep(current=>{ const next=current+1; navigator.vibrate?.(80); if(next>=protocol.targetSteps){window.clearInterval(timer);setRunning(false);window.setTimeout(()=>setScreen('results'),450);} return next;}),60000/protocol.cadenceBpm); return()=>window.clearInterval(timer);},[running,protocol.cadenceBpm,protocol.targetSteps]);
  const analysis=useMemo(()=>analyzeMotion(samples),[samples]);
  const progress=Math.min(100,(step/protocol.targetSteps)*100); const feuch=Math.min(99,Math.round(8+step*11+samples.length/20)); const reality=Math.max(1,100-Math.round(feuch*.36));
  const start=()=>{setStep(0);setSamples([]);startedAt.current=performance.now();setRunning(true);};
  return <main className="app-shell">
    <header className="hero"><div className="hero-mark">△</div><div className="hero-copy"><p className="eyebrow">FEUCH LAB INSTITUTE</p><h1>Dr. Marty's Walk Protocol</h1><p className="tagline">SIX STEPS. ANOTHER REALITY.</p></div><span className="badge">FLI-MW-06</span></header>
    {screen!=='intro'&&<nav className="phase-nav">{phases.map(p=><button key={p.id} className={screen===p.id?'phase active':'phase'} onClick={()=>!running&&setScreen(p.id)}><b>{p.n}</b><span>{p.label}</span></button>)}</nav>}
    <section className="panel">
      {screen==='intro'&&<div className="intro-screen"><p className="status">STATUS: PROBABLY SAFE</p><h2>Experimental Dimensional Locomotion System</h2><div className="intro-visual"><div className="portal"><span>6</span><small>STEPS</small></div></div><p>Expérience guidée inspirée du brevet abandonné US20060014125A1. Le document est réel ; ses effets hyperspatiaux ne sont pas de la physique établie.</p><div className="warning">Espace dégagé uniquement. Ne marchez jamais vers un mur, une porte, un escalier, du mobilier ou la circulation.</div><button className="primary big" onClick={()=>setScreen('setup')}>ENTRER DANS LE LABO</button></div>}
      {screen==='setup'&&<><p className="section-kicker">01 — PRÉPARER</p><h2>Calibration</h2><p className="lead">Le brevet calcule une longueur de foulée à partir de la masse. On vérifie ensuite l'espace disponible.</p><div className="grid compact-grid"><Field label="Poids (kg)" value={body.weightKg} onChange={v=>setBody({...body,weightKg:v})}/><Field label="Taille (cm)" value={body.heightCm} onChange={v=>setBody({...body,heightCm:v})}/><Field label="Pointure (EU)" value={body.shoeSizeEU} onChange={v=>setBody({...body,shoeSizeEU:v})}/><Field label="Espace libre (m)" value={body.availableDistanceM} step="0.1" onChange={v=>setBody({...body,availableDistanceM:v})}/></div><div className="distance-card"><span>Distance calculée</span><strong>{protocol.requiredDistanceM} m</strong><small>+ 1 m de marge recommandé</small><div className="distance-bar"><i style={{width:`${Math.min(100,protocol.requiredDistanceM/Math.max(.1,body.availableDistanceM)*100)}%`}}/></div></div>{!protocol.safe&&<div className="warning">Prévoir au moins {(protocol.requiredDistanceM+1).toFixed(1)} m totalement dégagés.</div>}<button className="primary big" onClick={()=>setScreen('protocol')}>VOIR COMMENT MARCHER →</button></>}
      {screen==='protocol'&&<><p className="section-kicker">02 — APPRENDRE</p><h2>La séquence</h2><p className="lead"><strong>6 pas · 1 pas/seconde · bras croisés.</strong></p><div className="walk-guide"><div className="posture-callout"><span>↳</span><b>BRAS CROISÉS</b><small>Regard droit · dos droit · marche naturelle</small></div><div className="walker-strip">{Array.from({length:6},(_,i)=><div className="walker-step" key={i}><div className="step-badge">{i+1}</div><div className={`walker ${i%2?'alt':''}`}><i className="head"/><i className="body"/><i className="arm a1"/><i className="arm a2"/><i className="leg l1"/><i className="leg l2"/></div><span>{i}s</span></div>)}</div><div className="route-line">{Array.from({length:6},(_,i)=><i key={i} className="foot" style={{left:`${8+i*17}%`}}/>)}</div><div className="route-measure">← {protocol.requiredDistanceM} m pour 6 pas →</div></div><div className="protocol-dashboard"><Metric label="Longueur de pas" value={`${protocol.strideLengthM} m`}/><Metric label="Cadence" value="1 pas/sec"/><Metric label="Pas" value="6"/><Metric label="Espace min." value={`${(protocol.requiredDistanceM+1).toFixed(1)} m`}/></div><button className="primary big" disabled={!protocol.safe} onClick={()=>setScreen('walk')}>JE SUIS PRÊT — LANCER</button></>}
      {screen==='walk'&&<><p className="section-kicker">03 — EXPÉRIMENTER</p><h2>{running?'Marchez maintenant':'Prêt ?'}</h2><div className={running?'experiment-stage running':'experiment-stage'}><div className="progress-ring" style={{'--progress':`${progress*3.6}deg`} as React.CSSProperties}><div><strong>{step}<small>/6</small></strong><span>{running?'PAS':'READY'}</span></div></div><div className="current-instruction"><div className="arms-icon"><i/><i/><b/></div><strong>BRAS CROISÉS</strong><span>{running?`Pas ${Math.min(step+1,6)} — avancez au bip`:'Téléphone près du corps'}</span></div><div className="live-track">{Array.from({length:6},(_,i)=><div key={i} className={i<step?'track-step done':i===step&&running?'track-step current':'track-step'}><b>{i+1}</b><small>{(protocol.strideLengthM*(i+1)).toFixed(2)} m</small></div>)}</div></div><div className="live-stats"><Metric label="Distance" value={`${Math.min(protocol.requiredDistanceM,protocol.strideLengthM*step).toFixed(2)} m`}/><Metric label="Capteur" value={String(samples.length)}/><Metric label="Feuch fiction" value={`${feuch}%`}/><Metric label="Réalité fiction" value={`${reality}%`}/></div><VortexMonitor activeCount={Math.min(8,Math.max(1,step+2))}/>{!running?<button className="primary launch" onClick={start}>▶ DÉMARRER LES 6 PAS</button>:<button className="danger big" onClick={()=>setRunning(false)}>■ ARRÊT</button>}</>}
      {screen==='results'&&<Results analysis={analysis} step={step} distance={protocol.requiredDistanceM} onRestart={()=>setScreen('setup')}/>} 
    </section><footer>BLACKLACE RESEARCH NETWORK // PETITS PAS, GRANDS DÉRAPAGES</footer>
  </main>;
}

function Results({analysis,step,distance,onRestart}:{analysis:ReturnType<typeof analyzeMotion>;step:number;distance:number;onRestart:()=>void}){
  const [debrief,setDebrief]=useState<CharacterDebrief[]>([]); const [source,setSource]=useState<'loading'|'octopus'|'fallback'>('loading'); const [selected,setSelected]=useState(0);
  useEffect(()=>{let alive=true; setSource('loading'); requestBlacklaceDebrief({analysis,steps:step,distanceM:distance}).then(result=>{if(!alive)return;setDebrief(result.characters);setSource(result.source);setSelected(0);}); return()=>{alive=false};},[analysis,step,distance]);
  const active=debrief[selected];
  return <div className="debrief-screen"><p className="section-kicker">04 — BLACKLACE DEBRIEF · OCTOPUS ENGINE</p><h2>{analysis.anomaly==='motion-spike'?'Anomalie à reproduire':'Expérience enregistrée'}</h2><div className="data-strip"><Metric label="Pas" value={`${step}/6`}/><Metric label="Durée" value={`${analysis.durationS}s`}/><Metric label="Pic" value={analysis.peakMagnitude==null?'—':`${analysis.peakMagnitude} m/s²`}/><Metric label="Variabilité" value={analysis.variability==null?'—':String(analysis.variability)}/></div><div className="evidence-tag">DATA // {analysis.sampleCount} mesures · {distance} m théoriques · {analysis.anomaly} · IA: {source==='loading'?'analyse…':source}</div><div className="character-tabs">{debrief.map((c,i)=><button key={c.name} className={i===selected?'active':''} onClick={()=>setSelected(i)}>{c.name}</button>)}</div><div className="octopus-comment">{source==='loading'?<><strong>OCTOPUS</strong><p>Analyse des mesures et consultation des portraits Blacklace…</p></>:active?<><header><strong>{active.name}</strong><span>{active.role}</span></header><p>{active.text}</p><small>{source==='octopus'?'Généré par Octopus à partir des données de cette session.':'Mode secours local — Octopus indisponible.'}</small></>:<p>Débrief indisponible.</p>}</div><button className="primary big" onClick={onRestart}>NOUVELLE EXPÉRIENCE</button></div>;
}
function Field({label,value,onChange,step}:{label:string;value:number;onChange:(v:number)=>void;step?:string}){return <label>{label}<input type="number" step={step} value={value} onChange={e=>onChange(Number(e.target.value))}/></label>}
function Metric({label,value}:{label:string;value:string}){return <div className="metric"><span>{label}</span><strong>{value}</strong></div>}
function VortexMonitor({activeCount}:{activeCount:number}){return <div className="body-monitor"><div className="body-silhouette"/>{vortexZones.map((z,i)=><div key={z.id} className={`vortex-node ${z.side} ${i<activeCount?'active':''}`} style={{top:`${z.y}%`}}><b>{z.id}</b><span>{z.name}</span></div>)}<small>MONITEUR VORTEX A–H · FICTION</small></div>}
